name:                httptest
version:             0.1.0.0
github:              "samroberton/httptest"
license:             BSD3
author:              "Sam Roberton"
maintainer:          "sam@samroberton.com"
copyright:           "Copyright Sam Roberton"

description:         Please see the README on GitHub at <https://github.com/samroberton/httptest#readme>

extra-source-files:
- README.md

ghc-options:
- -Werror
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- bytestring
- case-insensitive
- http-client
- http-types
- parsec
- text

library:
  source-dirs: src

executables:
  httptest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - httptest

tests:
  httptest-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - httptest
    - tasty
    - tasty-hunit
    - tasty-discover
    - wai
    - warp
