name:                httptest
version:             0.1.0.0
github:              "samroberton/httptest"
license:             BSD3
author:              "Sam Roberton"
maintainer:          "sam@samroberton.com"
copyright:           "Copyright Sam Roberton"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/samroberton/httptest#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  httptest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - httptest

tests:
  httptest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - httptest
